# Generated by Django 5.1.7 on 2026-03-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial en oficina'), ('virtual', 'Google Meet')], default='presencial', max_length=20, verbose_name='Tipo')),
                ('fecha_preferida', models.DateTimeField(verbose_name='Fecha y hora preferida')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje adicional')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de cita',
                'verbose_name_plural': 'Solicitudes de cita',
                'ordering': ['-recibido_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('proyecto_interes', models.CharField(blank=True, max_length=200, verbose_name='Proyecto de interés')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud de contacto',
                'verbose_name_plural': 'Solicitudes de contacto',
                'ordering': ['-recibido_en'],
            },
        ),
    ]
