# Generated by Django 6.0.3 on 2026-04-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcontacto',
            options={'ordering': ['-recibido_en'], 'verbose_name': 'Mensaje de contacto', 'verbose_name_plural': 'Mensajes de contacto'},
        ),
        migrations.AlterField(
            model_name='solicitudcita',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='solicitudcita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Cambia a "Confirmada" cuando agendes la reunión con el cliente.', max_length=20, verbose_name='Estado de la cita'),
        ),
        migrations.AlterField(
            model_name='solicitudcita',
            name='fecha_preferida',
            field=models.DateTimeField(help_text='Fecha y hora que el cliente eligió en el formulario.', verbose_name='Fecha y hora solicitada'),
        ),
        migrations.AlterField(
            model_name='solicitudcita',
            name='recibido_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Recibido en'),
        ),
        migrations.AlterField(
            model_name='solicitudcita',
            name='tipo',
            field=models.CharField(choices=[('presencial', 'Presencial en oficina'), ('virtual', 'Reunión por Google Meet')], default='presencial', help_text='Presencial en oficina o virtual por Google Meet.', max_length=20, verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='solicitudcontacto',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='solicitudcontacto',
            name='leido',
            field=models.BooleanField(default=False, help_text='Marca esto cuando ya hayas atendido al cliente.', verbose_name='Leído'),
        ),
        migrations.AlterField(
            model_name='solicitudcontacto',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje del cliente'),
        ),
        migrations.AlterField(
            model_name='solicitudcontacto',
            name='proyecto_interes',
            field=models.CharField(blank=True, help_text='Proyecto que el cliente seleccionó al enviar el formulario.', max_length=200, verbose_name='Proyecto de interés'),
        ),
        migrations.AlterField(
            model_name='solicitudcontacto',
            name='recibido_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Recibido en'),
        ),
    ]
