# Generated by Django 5.1.7 on 2026-03-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('nombre', models.CharField(blank=True, help_text='Ej: Piso 1, Penthouse', max_length=100, verbose_name='Nombre')),
                ('imagen_planta', models.ImageField(blank=True, null=True, upload_to='plantas/', verbose_name='Plano del nivel')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Nivel / Piso',
                'verbose_name_plural': 'Niveles / Pisos',
                'ordering': ['orden', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug URL')),
                ('descripcion_corta', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('descripcion', models.TextField(verbose_name='Descripción completa')),
                ('ubicacion', models.CharField(max_length=300, verbose_name='Ubicación')),
                ('google_maps_embed', models.TextField(blank=True, verbose_name='URL embed Google Maps')),
                ('imagen_fachada', models.ImageField(blank=True, null=True, upload_to='proyectos/', verbose_name='Imagen fachada')),
                ('imagen_isometrico', models.ImageField(blank=True, null=True, upload_to='proyectos/', verbose_name='Imagen isométrico')),
                ('catalogo_pdf', models.FileField(blank=True, null=True, upload_to='catalogos/', verbose_name='Catálogo PDF')),
                ('estado', models.CharField(choices=[('en_venta', 'En Venta'), ('preventa', 'En Preventa'), ('en_construccion', 'En Construcción'), ('vendido', 'Vendido')], default='en_venta', max_length=20, verbose_name='Estado')),
                ('precio_desde', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio desde (S/)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: 101, 202-A', max_length=20, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('1dorm', '1 Dormitorio'), ('2dorm', '2 Dormitorios'), ('3dorm', '3 Dormitorios'), ('duplex', 'Dúplex'), ('oficina', 'Oficina'), ('tienda', 'Tienda')], max_length=20, verbose_name='Tipo')),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área total (m²)')),
                ('area_techada', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área techada (m²)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio (S/)')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('separado', 'Separado'), ('vendido', 'Vendido')], default='disponible', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen_planta', models.ImageField(blank=True, null=True, upload_to='deptos/', verbose_name='Plano del depto')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='projects.nivel', verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nivel__numero', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='nivel',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='projects.proyecto', verbose_name='Proyecto'),
        ),
        migrations.CreateModel(
            name='ImagenGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/', verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Galería de imágenes',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='AvanceDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avances/', verbose_name='Imagen')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Avance de Obra',
                'verbose_name_plural': 'Avances de Obra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VideoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('youtube_url', models.URLField(verbose_name='URL de YouTube')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['orden'],
            },
        ),
    ]
