# Generated by Django 6.0.3 on 2026-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cci_dolares',
            field=models.CharField(blank=True, max_length=50, verbose_name='CCI (US$)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cci_soles',
            field=models.CharField(blank=True, max_length=50, verbose_name='CCI (S/)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cuenta_dolares',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cuenta corriente (US$)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cuenta_soles',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cuenta corriente (S/)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empresa_banco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empresa_receptora',
            field=models.CharField(blank=True, max_length=200, verbose_name='Empresa receptora'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='empresa_ruc',
            field=models.CharField(blank=True, max_length=20, verbose_name='RUC'),
        ),
    ]
