# Generated by Django 6.0.3 on 2026-04-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_banking_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagengaleria',
            options={'ordering': ['orden'], 'verbose_name': 'Foto de galería', 'verbose_name_plural': 'Galería de fotos'},
        ),
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['orden', 'numero'], 'verbose_name': 'Piso / Nivel', 'verbose_name_plural': 'Pisos / Niveles'},
        ),
        migrations.AlterModelOptions(
            name='videoproyecto',
            options={'ordering': ['orden'], 'verbose_name': 'Video del proyecto', 'verbose_name_plural': 'Videos del proyecto'},
        ),
        migrations.AlterField(
            model_name='avancedeobra',
            name='contenido',
            field=models.TextField(help_text='Texto que verán los clientes.', verbose_name='Descripción del avance'),
        ),
        migrations.AlterField(
            model_name='avancedeobra',
            name='fecha',
            field=models.DateField(help_text='Fecha en que se tomó la foto / se realizó el progreso.', verbose_name='Fecha del avance'),
        ),
        migrations.AlterField(
            model_name='avancedeobra',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto reciente de obra. Recomendado: 1200×800 px.', null=True, upload_to='avances/', verbose_name='Foto del avance'),
        ),
        migrations.AlterField(
            model_name='avancedeobra',
            name='publicado',
            field=models.BooleanField(default=True, help_text='Desmarca para ocultar este avance sin eliminarlo.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='avancedeobra',
            name='titulo',
            field=models.CharField(help_text='Ejemplo: "Avance estructural 60%", "Acabados terminados".', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='area_techada',
            field=models.DecimalField(decimal_places=2, help_text='Solo el área cerrada del departamento.', max_digits=8, verbose_name='Área techada (m²)'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='area_total',
            field=models.DecimalField(decimal_places=2, help_text='Suma de área techada + balcones / terrazas.', max_digits=8, verbose_name='Área total (m²)'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigo',
            field=models.CharField(help_text='Identificador interno. Ejemplo: 101, 202-A, PH1.', max_length=20, verbose_name='Código del depto'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalles adicionales: vista, orientación, características especiales.', verbose_name='Descripción (opcional)'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('separado', 'Separado'), ('vendido', 'Vendido')], default='disponible', help_text='Cuando un cliente separa un depto, este estado cambia automáticamente.', max_length=20, verbose_name='Estado de venta'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='imagen_planta',
            field=models.ImageField(blank=True, help_text='Plano específico de este departamento. Si lo dejas vacío, se usará el plano del nivel.', null=True, upload_to='deptos/', verbose_name='Plano del depto (opcional)'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='projects.nivel', verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='imagengaleria',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Texto que aparece debajo de la imagen al ampliarla.', max_length=200, verbose_name='Pie de foto (opcional)'),
        ),
        migrations.AlterField(
            model_name='imagengaleria',
            name='imagen',
            field=models.ImageField(help_text='Foto del proyecto (renders, ambientes, áreas comunes). Recomendado: 1600×1200 px.', upload_to='galeria/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='imagengaleria',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Menor número aparece primero en la galería.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='imagen_planta',
            field=models.ImageField(blank=True, help_text='Imagen del plano de planta de este nivel. PNG o JPG, recomendado 1200 px de ancho.', null=True, upload_to='plantas/', verbose_name='Plano del piso'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='nombre',
            field=models.CharField(blank=True, help_text='Ejemplo: "Piso 1", "Penthouse", "Sótano". Si lo dejas vacío se usará "Nivel N".', max_length=100, verbose_name='Nombre del nivel (opcional)'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='numero',
            field=models.PositiveIntegerField(help_text='Ejemplo: 1, 2, 3 (para sótanos puedes usar 0).', verbose_name='Número de piso'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Menor número aparece primero.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarca para ocultar el proyecto de la web sin eliminarlo.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='catalogo_pdf',
            field=models.FileField(blank=True, help_text='El cliente podrá descargarlo desde la página del proyecto.', null=True, upload_to='catalogos/', verbose_name='Catálogo en PDF (opcional)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cci_dolares',
            field=models.CharField(blank=True, max_length=50, verbose_name='CCI Dólares (interbancario)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cci_soles',
            field=models.CharField(blank=True, max_length=50, verbose_name='CCI Soles (interbancario)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cuenta_dolares',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cuenta corriente en Dólares (US$)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cuenta_soles',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cuenta corriente en Soles (S/)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(help_text='Texto largo que aparece en la página de detalle del proyecto.', verbose_name='Descripción completa'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion_corta',
            field=models.CharField(help_text='Texto breve que aparece en las tarjetas del listado de proyectos (máx. 300 caracteres).', max_length=300, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='empresa_banco',
            field=models.CharField(blank=True, help_text='Ejemplo: BCP - Banco de Crédito del Perú', max_length=100, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='empresa_receptora',
            field=models.CharField(blank=True, help_text='Razón social que aparece al cliente cuando elige "Transferencia".', max_length=200, verbose_name='Empresa receptora del pago'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('en_venta', 'En Venta'), ('preventa', 'En Preventa'), ('en_construccion', 'En Construcción'), ('vendido', 'Vendido')], default='en_venta', help_text='Determina la etiqueta de color que se muestra en el sitio.', max_length=20, verbose_name='Estado del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='google_maps_embed',
            field=models.TextField(blank=True, help_text='Pega aquí el código que copies de Google Maps (Compartir → Insertar mapa).', verbose_name='Mapa de Google (código embed)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen_fachada',
            field=models.ImageField(blank=True, help_text='Imagen principal del proyecto. Se muestra en el listado y como hero. Recomendado: 1200×800 px.', null=True, upload_to='proyectos/', verbose_name='Foto de fachada'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen_isometrico',
            field=models.ImageField(blank=True, help_text='Render 3D del edificio completo. Se muestra en la página de detalle.', null=True, upload_to='proyectos/', verbose_name='Render isométrico (opcional)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(help_text='Ejemplo: Boreal, Parke 10, IBYZA Tower', max_length=200, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Los proyectos con menor número aparecen primero en el sitio.', verbose_name='Orden de aparición'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='precio_desde',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio del departamento más barato disponible. Solo informativo.', max_digits=12, verbose_name='Precio desde (S/)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se genera automáticamente desde el nombre. No es necesario editarla.', unique=True, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ubicacion',
            field=models.CharField(help_text='Dirección o zona. Ejemplo: Umacollo, Arequipa.', max_length=300, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='videoproyecto',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Menor número aparece primero.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='videoproyecto',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título del video'),
        ),
        migrations.AlterField(
            model_name='videoproyecto',
            name='youtube_url',
            field=models.URLField(help_text='Pega la URL completa del video. Ejemplo: https://www.youtube.com/watch?v=ABC123', verbose_name='URL de YouTube'),
        ),
    ]
