# Generated by Django 6.0.5 on 2026-05-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_imagengaleria_options_alter_nivel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('separado', 'Separado'), ('vendido', 'Vendido')], db_index=True, default='disponible', help_text='Cuando un cliente separa un depto, este estado cambia automáticamente.', max_length=20, verbose_name='Estado de venta'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Desmarca para ocultar el proyecto de la web sin eliminarlo.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('en_venta', 'En Venta'), ('preventa', 'En Preventa'), ('en_construccion', 'En Construcción'), ('vendido', 'Vendido')], db_index=True, default='en_venta', help_text='Determina la etiqueta de color que se muestra en el sitio.', max_length=20, verbose_name='Estado del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Los proyectos con menor número aparecen primero en el sitio.', verbose_name='Orden de aparición'),
        ),
    ]
