# Generated by Django 6.0.5 on 2026-05-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_departamento_estado_alter_proyecto_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='codigo_acceso',
            field=models.CharField(blank=True, db_index=True, help_text='Código autogenerado para que el comprador vea el avance de obra. Compártelo con el cliente cuando se confirme la venta.', max_length=20, null=True, unique=True, verbose_name='Código de acceso del comprador'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='codigo_activo',
            field=models.BooleanField(default=True, help_text='Desmarca para revocar el acceso del comprador (ej: si rescindió la venta).', verbose_name='Código activo'),
        ),
    ]
