# Generated by Django 5.1.7 on 2026-03-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('hero', 'Inicio — Hero principal'), ('nosotros', 'Página Nosotros'), ('contacto', 'Página Contacto'), ('footer', 'Footer')], max_length=50, verbose_name='Sección')),
                ('clave', models.CharField(help_text='Ej: titulo, subtitulo, descripcion', max_length=100, verbose_name='Clave')),
                ('valor', models.TextField(blank=True, verbose_name='Texto')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contenido/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Contenido web',
                'verbose_name_plural': 'Contenidos web',
                'ordering': ['seccion', 'clave'],
                'unique_together': {('seccion', 'clave')},
            },
        ),
    ]
