# Generated by Django 6.0.3 on 2026-04-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='Puente Bolivar 205, Umacollo, Arequipa', max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(default='+51 993 674 174', max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(default='ventas@ibyzacorp.com', max_length=254, verbose_name='Correo')),
                ('horario', models.CharField(default='Lun-Vie: 9:00 AM - 6:00 PM | Sab: 9:00 AM - 1:00 PM', max_length=200, verbose_name='Horario')),
                ('whatsapp', models.CharField(default='+51993674174', max_length=50, verbose_name='WhatsApp')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/profile.php?id=61580984001744', verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('slogan', models.CharField(default='Tu mejor inversión al mejor precio y en la mejor ubicación', max_length=300, verbose_name='Slogan')),
                ('descripcion_empresa', models.TextField(default='Somos una empresa de servicios generales que cuenta con profesionales altamente calificados.', verbose_name='Descripción empresa')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
