# Generated by Django 6.0.3 on 2026-04-17 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_add_configuracion_sitio'),
        ('projects', '0002_add_banking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('icono', models.CharField(default='ShieldCheck', help_text='Nombre exacto de un icono de Lucide (e.g. "Home", "Key", "Award", "ShieldCheck")', max_length=50, verbose_name='Nombre de icono Lucide')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Beneficio / Valor',
                'verbose_name_plural': 'Beneficios / Valores',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300, verbose_name='Pregunta')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor orden aparece primero', verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Publicado')),
            ],
            options={
                'verbose_name': 'Pregunta frecuente',
                'verbose_name_plural': 'Preguntas frecuentes',
                'ordering': ['orden', 'pregunta'],
            },
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre cliente')),
                ('cargo', models.CharField(blank=True, max_length=200, verbose_name='Cargo / Ocupación')),
                ('testimonio', models.TextField(verbose_name='Testimonio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimonios/', verbose_name='Foto (opcional)')),
                ('calificacion', models.PositiveSmallIntegerField(default=5, help_text='Número de estrellas', verbose_name='Calificación (1-5)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Publicado')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonios', to='projects.proyecto', verbose_name='Proyecto relacionado')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['orden', '-id'],
            },
        ),
    ]
