# Generated by Django 6.0.3 on 2026-04-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_faq_testimonios_beneficios'),
        ('projects', '0003_alter_imagengaleria_options_alter_nivel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsitio',
            options={'verbose_name': 'Configuración general del sitio', 'verbose_name_plural': 'Configuración general del sitio'},
        ),
        migrations.AlterModelOptions(
            name='contenidoweb',
            options={'ordering': ['seccion', 'clave'], 'verbose_name': 'Texto e imagen del sitio', 'verbose_name_plural': 'Textos e imágenes del sitio'},
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarca para ocultar este beneficio sin borrarlo.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='descripcion',
            field=models.TextField(help_text='Explicación del beneficio (1-2 oraciones).', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='icono',
            field=models.CharField(default='ShieldCheck', help_text='Nombre exacto de un icono de Lucide. Lista: https://lucide.dev/icons. Ejemplos: Home, Key, Award, ShieldCheck.', max_length=50, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Menor número aparece primero.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='titulo',
            field=models.CharField(help_text='Frase corta. Ejemplo: "Ubicación estratégica", "Acabados premium".', max_length=150, verbose_name='Título del beneficio'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='descripcion_empresa',
            field=models.TextField(default='Somos una empresa de servicios generales que cuenta con profesionales altamente calificados.', help_text='Aparece en metadatos SEO y en algunas secciones del sitio.', verbose_name='Descripción de la empresa'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='direccion',
            field=models.CharField(default='Puente Bolivar 205, Umacollo, Arequipa', help_text='Aparece en el footer y en la página de contacto.', max_length=300, verbose_name='Dirección de oficina'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='email',
            field=models.EmailField(default='ventas@ibyzacorp.com', help_text='Correo público que se muestra a los clientes.', max_length=254, verbose_name='Correo de contacto'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://www.facebook.com/profile.php?id=61580984001744', help_text='URL completa del perfil de Facebook.', verbose_name='Enlace de Facebook'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='horario',
            field=models.CharField(default='Lun-Vie: 9:00 AM - 6:00 PM | Sab: 9:00 AM - 1:00 PM', max_length=200, verbose_name='Horario de atención'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL completa del perfil de Instagram.', verbose_name='Enlace de Instagram'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='Enlace de LinkedIn'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='slogan',
            field=models.CharField(default='Tu mejor inversión al mejor precio y en la mejor ubicación', help_text='Frase corta que aparece en el hero del sitio.', max_length=300, verbose_name='Slogan principal'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='telefono',
            field=models.CharField(default='+51 993 674 174', help_text='Incluye el código de país (+51 para Perú).', max_length=50, verbose_name='Teléfono principal'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='Enlace de TikTok'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='whatsapp',
            field=models.CharField(default='+51993674174', help_text='Sin espacios ni guiones. Ejemplo: +51993674174', max_length=50, verbose_name='Número de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='Enlace de YouTube'),
        ),
        migrations.AlterField(
            model_name='contenidoweb',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarca para ocultar este contenido sin borrarlo.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='contenidoweb',
            name='clave',
            field=models.CharField(help_text='Nombre técnico (no editar si no sabes qué es). Ejemplos: titulo, subtitulo, descripcion.', max_length=100, verbose_name='Identificador interno'),
        ),
        migrations.AlterField(
            model_name='contenidoweb',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Solo para textos que también requieren una imagen (ejemplo: hero principal).', null=True, upload_to='contenido/', verbose_name='Imagen asociada (opcional)'),
        ),
        migrations.AlterField(
            model_name='contenidoweb',
            name='seccion',
            field=models.CharField(choices=[('hero', 'Inicio — Sección principal (hero)'), ('nosotros', 'Página Nosotros'), ('contacto', 'Página Contacto'), ('footer', 'Pie de página (footer)')], help_text='En qué parte del sitio aparece este texto.', max_length=50, verbose_name='Sección de la web'),
        ),
        migrations.AlterField(
            model_name='contenidoweb',
            name='valor',
            field=models.TextField(blank=True, help_text='Lo que verá el cliente en el sitio.', verbose_name='Texto que se muestra'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarca para ocultar esta pregunta sin borrarla.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Menor número aparece primero en la sección de FAQ.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarca para ocultar este testimonio sin borrarlo.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='calificacion',
            field=models.PositiveSmallIntegerField(default=5, help_text='Cantidad de estrellas que se muestran junto al testimonio.', verbose_name='Calificación (1 a 5 estrellas)'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='cargo',
            field=models.CharField(blank=True, help_text='Ejemplo: "Cliente de Boreal", "Inversionista". Opcional.', max_length=200, verbose_name='Cargo / Ocupación'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='foto',
            field=models.ImageField(blank=True, help_text='Idealmente cuadrada, recomendado 400×400 px.', null=True, upload_to='testimonios/', verbose_name='Foto del cliente (opcional)'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Menor número aparece primero.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='proyecto',
            field=models.ForeignKey(blank=True, help_text='Si el testimonio menciona un proyecto en particular, selecciónalo aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonios', to='projects.proyecto', verbose_name='Proyecto relacionado (opcional)'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='testimonio',
            field=models.TextField(help_text='Cita textual del cliente.', verbose_name='Texto del testimonio'),
        ),
    ]
