# Generated by Django 6.0.5 on 2026-05-06 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_configuracionsitio_options_and_more'),
        ('projects', '0003_alter_imagengaleria_options_alter_nivel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='meet_link_permanente',
            field=models.URLField(blank=True, help_text='Pega aquí un link de Meet permanente (ej: meet.google.com/abc-defg-hij). Se incluirá en la confirmación de citas virtuales.', verbose_name='Link permanente de Google Meet'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_activo',
            field=models.BooleanField(default=False, help_text='Marca esto para mostrar un modal cuando el visitante entra al sitio (una vez por sesión).', verbose_name='Modal de bienvenida activo'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_cta_es_whatsapp',
            field=models.BooleanField(default=False, help_text='Si lo activas, el botón del modal abre WhatsApp con un mensaje pre-armado.', verbose_name='El botón abre WhatsApp en lugar del proyecto'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_cta_texto',
            field=models.CharField(blank=True, default='Ver proyecto', max_length=100, verbose_name='Texto del botón del modal'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_imagen',
            field=models.ImageField(blank=True, help_text='Imagen destacada del modal. Recomendado: 1200×800 px, máximo 500 KB.', null=True, upload_to='modal/', verbose_name='Imagen del modal'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_proyecto',
            field=models.ForeignKey(blank=True, help_text='Si seleccionas un proyecto, el botón del modal lleva a su página.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.proyecto', verbose_name='Proyecto destacado en modal'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_subtitulo',
            field=models.TextField(blank=True, default='Departamentos disponibles con la mejor ubicación de Arequipa.', verbose_name='Subtítulo del modal'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='modal_titulo',
            field=models.CharField(blank=True, default='Conoce nuestro nuevo proyecto', max_length=200, verbose_name='Título del modal'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='origen_nombre_texto',
            field=models.TextField(blank=True, default='El nombre IBYZA surge de la unión de los apellidos Ibáñez y Zavala, fundadores de la empresa.', help_text='Aparece al final de la página de inicio. Edítalo cuando quieras.', verbose_name='Texto sobre el origen del nombre IBYZA'),
        ),
    ]
