# Generated by Django 6.0.5 on 2026-05-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_configuracionsitio_meet_link_permanente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Desmarca para ocultar este beneficio sin borrarlo.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Menor número aparece primero.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='contenidoweb',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Desmarca para ocultar este contenido sin borrarlo.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='contenidoweb',
            name='seccion',
            field=models.CharField(choices=[('hero', 'Inicio — Sección principal (hero)'), ('nosotros', 'Página Nosotros'), ('contacto', 'Página Contacto'), ('footer', 'Pie de página (footer)')], db_index=True, help_text='En qué parte del sitio aparece este texto.', max_length=50, verbose_name='Sección de la web'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Desmarca para ocultar esta pregunta sin borrarla.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Menor número aparece primero en la sección de FAQ.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Desmarca para ocultar este testimonio sin borrarlo.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Menor número aparece primero.', verbose_name='Orden'),
        ),
    ]
