# Generated by Django 6.0.5 on 2026-05-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_beneficio_activo_alter_beneficio_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='politicas_privacidad_html',
            field=models.TextField(blank=True, default='<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod, nibh ac vulputate efficitur, urna nulla finibus odio.</p><p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>', help_text='Soporta HTML basico (p, ul, li, strong, br). Aparece en el modal de "Acepto las politicas de privacidad" del formulario de cita.', verbose_name='Texto de Politicas de Privacidad (HTML)'),
        ),
    ]
