# Generated by Django 6.0.5 on 2026-05-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_configuracionsitio_politicas_privacidad_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidoweb',
            options={'ordering': ['pagina', 'seccion', 'orden', 'clave'], 'verbose_name': 'Texto e imagen del sitio', 'verbose_name_plural': 'Textos e imágenes del sitio'},
        ),
        migrations.AlterUniqueTogether(
            name='contenidoweb',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contenidoweb',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Menor número aparece primero.', verbose_name='Orden dentro de la sección'),
        ),
        migrations.AddField(
            model_name='contenidoweb',
            name='pagina',
            field=models.CharField(choices=[('inicio', 'Página Inicio'), ('nosotros', 'Página Nosotros'), ('proyectos', 'Página Proyectos'), ('separar', 'Página Separar'), ('contacto', 'Página Contacto'), ('global', 'Global (footer, modales)')], db_index=True, default='inicio', help_text='Página del sitio donde aparece este contenido.', max_length=20, verbose_name='Página de la web'),
        ),
        migrations.AlterField(
            model_name='contenidoweb',
            name='seccion',
            field=models.CharField(choices=[('hero', 'Hero principal'), ('quienes_somos', 'Quiénes Somos'), ('mision_vision', 'Misión / Visión / Compromiso'), ('valores', 'Lo que nos define (valores)'), ('cta_final', 'CTA inferior'), ('carrusel', 'Carrusel de proyectos'), ('info_contacto', 'Información de contacto'), ('formulario', 'Formulario'), ('footer', 'Pie de página'), ('modal_bienvenida', 'Modal de bienvenida')], db_index=True, help_text='Bloque dentro de la página (Hero, CTA, Misión, etc.).', max_length=50, verbose_name='Sección dentro de la página'),
        ),
        migrations.AlterUniqueTogether(
            name='contenidoweb',
            unique_together={('pagina', 'seccion', 'clave')},
        ),
    ]
