# Generated by Django 6.0.5 on 2026-05-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_data_reasignar_pagina_seccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficio',
            options={'ordering': ['orden'], 'verbose_name': 'Valor / Beneficio', 'verbose_name_plural': 'Valores / Beneficios'},
        ),
        migrations.AddField(
            model_name='beneficio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen que aparece de fondo en la card del valor. Recomendado: 800×600 px, máximo 400 KB. Si no subís imagen, la card queda con fondo oscuro plano.', null=True, upload_to='valores/', verbose_name='Imagen de fondo'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='activo',
            field=models.BooleanField(db_index=True, default=True, help_text='Desmarca para ocultar este valor sin borrarlo.', verbose_name='Visible en el sitio'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='descripcion',
            field=models.TextField(help_text='Frase explicativa (1-2 oraciones).', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='icono',
            field=models.CharField(default='ShieldCheck', help_text='Nombre exacto de un icono de Lucide (https://lucide.dev/icons). Ejemplos: Shield, Star, Zap, Heart, Users, Award.', max_length=50, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Menor número aparece primero en el carrusel.', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='titulo',
            field=models.CharField(help_text='Nombre corto. Ejemplo: "Compromiso", "Calidad", "Innovación".', max_length=150, verbose_name='Título del valor'),
        ),
    ]
