# Generated by Django 6.0.5 on 2026-05-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_data_seed_valores_iniciales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreguntaFrecuente',
        ),
        migrations.DeleteModel(
            name='Testimonio',
        ),
    ]
