# Generated by Django 6.0.5 on 2026-05-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_data_limpiar_entry_valores_huerfano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='email',
            field=models.EmailField(default='renata.delgado@ibyzacorp.com', help_text='Correo público que se muestra a los clientes.', max_length=254, verbose_name='Correo de contacto'),
        ),
    ]
