# Generated by Django 6.0.8 on 2026-09-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_configuracionsitio_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='icono',
            field=models.CharField(choices=[('Shield', 'Escudo'), ('ShieldCheck', 'Escudo con check'), ('BadgeCheck', 'Insignia verificada'), ('Lock', 'Candado'), ('Star', 'Estrella'), ('Sparkles', 'Destellos'), ('Award', 'Medalla'), ('Trophy', 'Trofeo'), ('Gem', 'Gema'), ('Users', 'Personas'), ('Heart', 'Corazón'), ('HandHeart', 'Mano con corazón'), ('Handshake', 'Apretón de manos'), ('Zap', 'Rayo'), ('Lightbulb', 'Bombilla / idea'), ('TrendingUp', 'Crecimiento'), ('Target', 'Objetivo'), ('Compass', 'Brújula'), ('Building2', 'Edificio'), ('Home', 'Casa'), ('Key', 'Llave'), ('MapPin', 'Ubicación'), ('Hammer', 'Martillo'), ('Ruler', 'Regla'), ('Leaf', 'Hoja / sostenibilidad'), ('Recycle', 'Reciclaje'), ('CheckCircle2', 'Check en círculo'), ('Clock', 'Reloj')], default='Shield', help_text='Elige el icono de la lista. Solo aparecen los iconos que el sitio tiene compilados; si necesitas uno nuevo, pídelo a COREM.', max_length=50, verbose_name='Icono'),
        ),
    ]
