# Generated by Django 5.1.7 on 2026-03-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Separacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto (S/)')),
                ('culqi_charge_id', models.CharField(blank=True, max_length=200, verbose_name='ID de pago Culqi')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('error', models.TextField(blank=True, verbose_name='Detalle de error')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='separaciones', to='projects.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Separación',
                'verbose_name_plural': 'Separaciones',
                'ordering': ['-registrado_en'],
            },
        ),
    ]
