# Generated by Django 6.0.3 on 2026-03-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='separacion',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de transferencia'),
        ),
        migrations.AddField(
            model_name='separacion',
            name='metodo_pago',
            field=models.CharField(choices=[('culqi', 'Tarjeta (Culqi)'), ('transferencia', 'Transferencia bancaria')], default='culqi', max_length=20, verbose_name='Método de pago'),
        ),
    ]
