# Generated by Django 6.0.3 on 2026-04-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_separacion_comprobante_separacion_metodo_pago'),
        ('projects', '0003_alter_imagengaleria_options_alter_nivel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separacion',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido del comprador'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='comprobante',
            field=models.ImageField(blank=True, help_text='El comprador sube esta imagen desde la web. Solo aplica si pagó por transferencia.', null=True, upload_to='comprobantes/', verbose_name='Comprobante de transferencia'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='culqi_charge_id',
            field=models.CharField(blank=True, help_text='Solo lectura. Se llena automáticamente cuando el pago es con tarjeta.', max_length=200, verbose_name='ID de transacción Culqi'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='separaciones', to='projects.departamento', verbose_name='Departamento separado'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='dni',
            field=models.CharField(help_text='Documento Nacional de Identidad del comprador (8 dígitos).', max_length=20, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo del comprador'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='error',
            field=models.TextField(blank=True, help_text='Si Culqi rechaza el pago, aquí queda registrado el motivo.', verbose_name='Detalle de error técnico (solo lectura)'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('completado', 'Aprobada / Completada'), ('fallido', 'Rechazada / Fallida')], default='pendiente', help_text='Si pagó con tarjeta, se marca automáticamente como "Completada". Si fue por transferencia, debes aprobarla tú.', max_length=20, verbose_name='Estado de la separación'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='metodo_pago',
            field=models.CharField(choices=[('culqi', 'Tarjeta (Culqi)'), ('transferencia', 'Transferencia bancaria')], default='culqi', help_text='Tarjeta (Culqi) se aprueba automáticamente. Transferencia requiere tu aprobación manual.', max_length=20, verbose_name='Método de pago usado'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto que el cliente pagó como separación.', max_digits=12, verbose_name='Monto separado (S/)'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del comprador'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='registrado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrada el'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono del comprador'),
        ),
    ]
