# Generated by Django 6.0.5 on 2026-05-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_separacion_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='separacion',
            name='notas_admin',
            field=models.TextField(blank=True, help_text='Notas privadas para el equipo. No se muestran al comprador.', verbose_name='Notas internas (solo admin)'),
        ),
        migrations.AddField(
            model_name='separacion',
            name='numero_operacion',
            field=models.CharField(blank=True, help_text='Número de operación bancaria, voucher de efectivo o referencia del cheque.', max_length=100, verbose_name='N° de operación / referencia'),
        ),
        migrations.AddField(
            model_name='separacion',
            name='origen',
            field=models.CharField(choices=[('web', 'Formulario público'), ('admin', 'Registro manual (admin)')], db_index=True, default='web', help_text='Indica si la separación entró por la web pública o se registró manualmente desde el admin.', max_length=10, verbose_name='Origen del registro'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='comprobante',
            field=models.ImageField(blank=True, help_text='Imagen del voucher, comprobante de transferencia o cheque.', null=True, upload_to='comprobantes/', verbose_name='Comprobante de pago'),
        ),
        migrations.AlterField(
            model_name='separacion',
            name='metodo_pago',
            field=models.CharField(choices=[('culqi', 'Tarjeta (Culqi)'), ('transferencia', 'Transferencia bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='culqi', help_text='Tarjeta (Culqi) se aprueba automáticamente. Transferencia, efectivo y cheque requieren aprobación manual.', max_length=20, verbose_name='Método de pago usado'),
        ),
    ]
