web: gunicorn ibyza.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
release: python manage.py migrate --noinput && python manage.py createcachetable django_cache_table && python manage.py create_admin
